# revision 25980
# category Package
# catalog-ctan /info/examples/Einfuehrung
# catalog-date 2012-04-08 22:46:50 +0200
# catalog-license lppl1.3
# catalog-version undef
Name:		texlive-einfuehrung
Version:	20120408
Release:	1
Summary:	Examples from the book Einfuhrung in LaTeX
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/info/examples/Einfuehrung
License:	LPPL1.3
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/einfuehrung.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/einfuehrung.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg

%description
The bundle consists of examples and data files for the DANTE-
Edition book "Einfuhrung in LaTeX".

#-----------------------------------------------------------------------
%files
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-1.ltxverb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-2.xltxverb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-3.luaverb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-03-1.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-03-2.ctx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-03-3.ctxcrop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-3.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-4.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-5.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-6.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-05-7.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-06-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-06-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-06-4.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-06-5.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-06-6.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-10.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-12.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-07-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-3.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-5.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-6.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/03-08-7.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-4.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-5.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-6.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-7.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-02-9.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-03-5.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-04-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/04-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-01-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-01-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-01-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-01-4.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-10.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-11.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-12.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-13.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-5.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-6.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-7.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-8.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-02-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-12.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-4.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-11.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-04-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-3.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-4.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-8.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-07-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-08-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-08-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-7.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-8.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-09-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-10-9.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-8.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-11-9.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-12-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-12-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-12-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-13-1.ltx1
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-13-2.ltx1
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-13-3.ltx1ps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-13-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-13-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-14-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-14-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-14-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-15-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-15-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-15-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-15-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/05-16-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-1.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-02-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-100.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-101.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-102.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-103.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-104.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-105.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-106.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-107.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-108.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-109.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-110.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-111.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-112.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-113.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-114.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-115.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-116.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-117.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-118.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-119.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-120.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-121.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-122.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-123.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-124.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-125.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-126.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-127.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-128.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-129.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-130.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-131.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-132.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-133.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-134.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-135.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-136.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-137.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-17.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-18.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-24.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-25.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-26.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-27.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-28.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-29.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-30.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-32.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-33.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-34.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-35.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-36.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-37.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-38.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-39.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-40.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-41.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-42.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-43.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-44.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-45.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-46.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-47.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-48.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-49.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-50.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-51.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-52.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-53.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-54.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-55.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-56.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-57.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-58.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-59.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-60.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-61.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-62.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-63.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-64.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-65.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-66.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-67.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-68.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-69.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-70.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-71.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-72.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-73.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-74.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-75.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-76.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-77.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-78.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-79.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-80.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-81.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-82.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-83.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-84.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-85.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-86.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-87.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-88.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-89.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-90.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-91.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-92.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-93.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-94.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-95.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-96.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-97.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-98.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/06-03-99.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-00-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-01-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-02-5.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/07-04-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-02-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-02-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-02-3.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-04-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-04-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-3.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-4.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-5.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-6.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-05-7.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-10.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-11.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-12.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-13.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-3.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-4.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-5.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-6.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-7.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-8.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-06-9.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-1.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-10.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-11.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-12.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-14.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-17.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-18.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-24.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-25.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-26.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-27.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-28.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-29.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-3.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-30.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-32.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-4.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-5.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-6.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-7.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-8.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-07-9.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-10.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-11.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-08-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-09-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-09-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-09-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/08-09-4.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-8.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-03-9.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-05-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-17.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-18.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-24.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-25.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-26.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-27.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-28.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-29.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-30.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-32.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-33.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-34.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-35.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-36.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-37.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-38.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-39.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-40.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-41.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-42.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-43.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-44.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-45.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-46.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-47.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-48.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-49.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-06-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-17.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-18.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-24.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-25.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-26.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-27.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-28.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-29.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-30.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-32.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-33.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-34.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-35.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-36.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-37.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-38.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-39.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-40.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-41.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-42.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-43.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-44.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-45.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-46.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-47.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-48.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-49.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-50.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-51.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-52.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-53.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-54.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-55.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-56.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-57.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-58.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-59.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-60.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-61.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-62.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-63.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-64.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-65.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-07-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-17.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-18.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-24.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-25.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-26.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-27.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-28.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-29.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-30.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-32.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-33.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-34.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-35.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-36.ltx4
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-37.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-38.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-39.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-40.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-41.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-42.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-43.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-44.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-45.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-46.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/09-08-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-01-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-01-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-05-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-05-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-05-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-05-4.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-06-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-10.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-11.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-12.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-13.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-17.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-18.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-19.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-20.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-24.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-25.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-26.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-27.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-28.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-29.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-3.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-30.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-32.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-7.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-07-9.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-10.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-2.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-3.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-5.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-6.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-7.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/10-08-9.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-15.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-16.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-17.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-18.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-05-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-06-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/11-07-1.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-1.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-10.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-11.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-12.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-13.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-2.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-3.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-4.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-5.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-6.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-7.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-8.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-01-9.xinl
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-1.sh
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-10.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-11.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-12.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-13.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-14.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-15.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-16.lualtx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-17.lualtx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-18.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-2.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-3.sh
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-4.sh
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-5.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-6.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-7.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-8.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/12-04-9.lualtx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-01-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-01-2.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-01-3.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-01-4.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-10.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-11.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-12.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-13.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-14.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-15.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-16.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-17.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-18.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-19.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-2.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-20.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-3.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-4.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-5.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-6.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-7.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-8.ltxbps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-02-9.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-10.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-11.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-2.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-3.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-4.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-5.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-6.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-7.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-8.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-03-9.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-04-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-04-2.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-05-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-05-2.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-05-3.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-05-4.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-06-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-06-2.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-07-1.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/13-07-2.ltxb
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-8.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-01-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-02-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-10.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-15.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-16.ltx2crop
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-03-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-04-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/14-05-1.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-01-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-1.mp3
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-10.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-11.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-12.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-13.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-14.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-15.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-16.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-17.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-18.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-19.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-2.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-20.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-21.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-22.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-23.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-24.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-25.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-26.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-27.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-28.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-29.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-30.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-31.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-32.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-33.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-34.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-35.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-36.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-37.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-38.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-39.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-4.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-40.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-41.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-42.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-43.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-44.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-45.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-46.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-47.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-48.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-49.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-5.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-50.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-51.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-52.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-53.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-54.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-55.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-56.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-57.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-58.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-59.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-6.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-60.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-61.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-62.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-63.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-64.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-65.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-66.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-67.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-68.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-69.mp2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-7.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-8.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-02-9.mp
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-1.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-10.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-11.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-12.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-13.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-14.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-15.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-16.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-17.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-18.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-19.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-2.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-20.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-21.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-22.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-23.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-24.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-25.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-26.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-27.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-28.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-29.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-3.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-30.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-31.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-32.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-33.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-34.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-35.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-36.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-37.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-38.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-39.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-4.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-40.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-41.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-42.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-43.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-44.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-45.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-46.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-47.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-48.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-49.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-5.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-50.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-51.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-6.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-7.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-8.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-03-9.ltxps
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-10.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-11.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-12.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-13.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-14.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-15.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-16.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-17.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-18.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-19.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-20.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-21.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-22.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-23.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-24.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-25.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-26.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-27.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-28.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-29.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-30.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-31.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-32.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-33.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-34.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-35.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-36.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-37.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-38.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-39.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-40.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-41.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-42.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-43.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-44.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-45.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-46.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-47.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-48.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-49.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-50.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-51.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-52.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-53.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-54.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-55.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-56.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-57.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-58.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-59.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-60.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-61.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-62.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-63.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-64.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-65.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-66.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-67.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-68.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-69.ltx4
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-7.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-70.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-71.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-72.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-73.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-74.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-75.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-76.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-77.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-78.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-79.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-8.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-80.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/15-04-9.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-02-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-03-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-04-1.ltx2
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-04-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-04-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-04-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-04-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-12-1.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-12-2.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-12-3.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-12-4.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-12-5.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/A-12-6.ltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/B.pdf
%doc %{_texmfdistdir}/doc/latex/einfuehrung/CTdefault.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/DEexa.sty
%doc %{_texmfdistdir}/doc/latex/einfuehrung/DEoptions.sty
%doc %{_texmfdistdir}/doc/latex/einfuehrung/Letter.ist
%doc %{_texmfdistdir}/doc/latex/einfuehrung/LetterC.ist
%doc %{_texmfdistdir}/doc/latex/einfuehrung/LoadFonts.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/README
%doc %{_texmfdistdir}/doc/latex/einfuehrung/UTF8.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/VerbatimOut.xltx
%doc %{_texmfdistdir}/doc/latex/einfuehrung/beispiel.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/biblatex-examples.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/bspcalweekly.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/bspdvdcoll.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/bspfont.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/bsppstricks.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/data0.csv
%doc %{_texmfdistdir}/doc/latex/einfuehrung/data1T.csv
%doc %{_texmfdistdir}/doc/latex/einfuehrung/de-examples-dw.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/demo.ist
%doc %{_texmfdistdir}/doc/latex/einfuehrung/demo11.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/demo4.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/demo5.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/demo6.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/demo7.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/doc_data.txt
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exa-fontconfig.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaarticle.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaarticle2.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaartplain.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exabeamer.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exabook.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exabook2.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exadante.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exafoils.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exafubeamer.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exafupd.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examargin.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examemoir.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examinimal-mathsymbols.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examinimal.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examples-dw.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examples.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examplesA.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/examplesB.bib
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exapd.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaprosper.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exareport.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaseminar.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaslidenotes.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exasymbol.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/exaxetex.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/fontDemo-E.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/fontDemo.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/foo.lua
%doc %{_texmfdistdir}/doc/latex/einfuehrung/mpxerr.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleB.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleC.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleE.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleF.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleG.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleH.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/myModuleI.xdy
%doc %{_texmfdistdir}/doc/latex/einfuehrung/plainDemo.bst
%doc %{_texmfdistdir}/doc/latex/einfuehrung/preamble.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/screxa.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/screxabook.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/screxareport.cls
%doc %{_texmfdistdir}/doc/latex/einfuehrung/tab.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/tabelle1.tex
%doc %{_texmfdistdir}/doc/latex/einfuehrung/textdemo.sty

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar doc %{buildroot}%{_texmfdistdir}
